server:
  servlet:
    context-path: /edu
  port: 8001

minio:
  endpoint: http://123.57.213.188
  port: 9000
  accessKey: AKIAIOSFODNN7EXAMPLE
  secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  bucketName: edu-source
  path:
    image:
      # 课程封面
      course-cover: /image/course-cover/

spring:
  application:
    name: service-edu
  datasource:
    druid:
      url: jdbc:mysql://47.111.28.188:3306/knife_edu?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      # Spring Boot 默认是不注入这些属性值的，需要自己绑定
      # druid 数据源专有配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache
      poolPreparedStatements: true
      # 配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
      # 如果运行时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
      # 则导入 log4j 依赖即可，Maven 地址： https://mvnrepository.com/artifact/log4j/log4j
      filters: stat,wall,slf4j,config
      # 指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#      stat-view-servlet:
#        enabled: true
  servlet:
    # 文件上传配置
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  type-aliases-package: "com.knife"
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      id-type: ID_WORKER_STR
      update-strategy: NOT_NULL